title:
  base-length: 15
  longer-length: 20

bio:
  base-length: 15
  longer-length: 20

elytra-drop-chance: 0.2
  
bans-broadcast:
  channel: bans-mutes
  allowed:
    - muted
    - warned
    - warned.offline
    - broadcast

disable-chorus-tp: true

phantoms-disabled-by-default: true

# DO NOT CHANGE THIS OR THE PLUGIN WILL BREAK
config-version: 1