name: Ukutils
version: '${version}'
main: net.uku3lig.ukutils.Ukutils
api-version: 1.17
softdepend: [ LuckPerms, VentureChat, LiteBans, UltimateTimber ]
authors: [ uku ]
description: a few utility commands
commands:
  color:
    description: Change the color of your username
    usage: /color [user] <color>
    permission: ukutils.color
  title:
    description: Give yourself a title (max 15 chars)
    usage: /title [user] <text>
    permission: ukutils.title
  bio:
    description: Give yourself a title (max 15 chars)
    usage: /bio [user] <text>
    permission: ukutils.bio
  boat:
    description: Spawns a boat
    usage: /boat
    permission: ukutils.boat
  nether:
    description: Sends you to the nether
    usage: /nether
    permission: ukutils.nether
  end:
    description: Sends you to the end
    usage: /end
    permission: ukutils.end
  toggletimber:
    aliases: [ toggletreefeller ]
    description: Toggles tree feller
    usage: /toggletimber
    permission: ukutils.toggletimber
  enderchest:
    aliases: [ ec ]
    description: Opens your enderchest
    usage: /enderchest [player]
    permission: ukutils.ec
  killboats:
    description: Kills all empty boats
    usage: /killboats
    permission: ukutils.killboats
  shrug:
    description: shrugging
    usage: /shrug
    permission: ukutils.shrug
  togglephantoms:
    description: toggles phantoms for the player
    usage: /togglephantoms
    permission: ukutils.togglephantoms
permissions:
  ukutils.color:
    description: allows you to change your username color
    default: true
  ukutils.color.rgb:
    description: allows use of rgb color codes
    default: true
  ukutils.color.others:
    description: allow to change other users' colors
    default: op
  ukutils.title:
    description: allows you to add a title before your username
    default: true
  ukutils.title.longer:
    description: allows for a longer title
    default: true
  ukutils.title.others:
    description: allows to change others' title
    default: op
  ukutils.bio:
    description: allows to have a bio
    default: true
  ukutils.bio.longer:
    description: allows for a longer bio
    default: true
  ukutils.bio.others:
    description: allows to change others' bio
    default: op
  ukutils.boat:
    description: allows you to spawn a boat
    default: true
  ukutils.nether:
    description: allows you to tp to the nether
    default: op
  ukutils.end:
    description: allows you to tp to the end
    default: op
  ukutils.toggletimber:
    description: allows you to toggle UltimateTimber
    default: true
  ukutils.ec:
    description: allows you to access your enderchest
    default: true
  ukutils.ec.others:
    description: allows you to see others' enderchests
    default: op
  ukutils.killboats:
    description: allows you to kill all empty boats
    default: op
  ukutils.shrug:
    description: ":shrug:"
    default: true
  ukutils.elytra:
    description: allows you to renew elytras
    default: true
  ukutils.togglephantoms:
    description: allows you to toggle phantoms
    default: true